apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wrw-tls
  namespace: sandbox
spec:
  secretName: wrw-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - wrw.app
